/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 20 18:55:09 GMT 2017
 */

package org.cs362.dominion;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.cs362.dominion.RandomTestDominion;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.Random;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = false, useVFS = false, useVNET = false, resetStaticState = false, separateClassLoader = false, useJEE = false)
public class RandomTestDominion_ESTest {

  /*@Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Random.setNextRandom(283);
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        RandomTestDominion.main(stringArray0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.cs362.dominion.Card", e);
      }
  }*/

  /*@Test(timeout = 4000)
  public void test1()  throws Throwable  {
      String[] stringArray0 = new String[4];
      // Undeclared exception!
      RandomTestDominion.main(stringArray0);
  }*/

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      RandomTestDominion randomTestDominion0 = new RandomTestDominion();
  }
}
